cd A.I.Files
start python aa-execute.py
start python ab-execute.py
start python ac-execute.py
start python ad-execute.py
start python ae-execute.py
start python af-execute.py
start python ag-execute.py
start python ah-execute.py
start python ai-execute.py
start python aj-execute.py
start python ak-execute.py
start python al-execute.py
start python am-execute.py
start python an-execute.py
start python ao-execute.py
start python ap-execute.py
start python aq-execute.py
start python ar-execute.py
start python as-execute.py
start python at-execute.py
start python au-execute.py
start python av-execute.py
start python aw-execute.py
start python ax-execute.py
start python ay-execute.py
start python az-execute.py